# https://taskfile.dev

version: '3'

vars:
  CMD: ./cmd/wink

tasks:

  build:
    desc: Build binary
    cmds:
      - go build -ldflags="-s -w" -o {{.BUILD}}/{{.BINARY}} {{.CMD}}
    vars:
      BUILD: ./build
      BINARY: wink.exe

  install:
    desc: Install binary locally
    cmds:
      - go install -ldflags="-s -w" {{.CMD}}
      - upx --brute {{.BINARY}}
      - ls -la {{.BINARY}}
    vars:
      BINARY: $(go env GOPATH)/bin/wink
