# https://taskfile.dev

version: '3'

vars:
  CMD: ./cmd/wink

tasks:
  install:
    desc: Install binary locally
    cmds:
      - go install -ldflags="-s -w" {{.CMD}}
      - upx --brute {{.BINARY}}
      - ls -la {{.BINARY}}
    vars:
      BINARY: $(go env GOPATH)/bin/wink
