name: Releaser

on:
  push:
    branches:
      - "*"

jobs:
  # -------- Test job -------- #
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Test
        run: go test -v ./...
